Changing context to fs.

diff --git a/hooks/test b/hooks/test
--- a/hooks/test
+++ b/hooks/test
@@ -3,26 +3,8 @@
 set -e
 
 CONTAINER=grr_container
-MAX_START_WAIT_SECS=300
-
-function wait_for_container_to_start() {
-  echo "Waiting for container to start.."
-  poll_start=$(date +%s)
-  while true; do
-    ready_msg="$(docker logs ${CONTAINER} 2>&1 | perl -wln -e 'print if /\bAdmin UI gui is at\b/')"
-    if [[ ! -z "${ready_msg}" ]]; then
-      break
-    fi
-    secs_elapsed=$(( $(date +%s) - $poll_start ))
-    if [[ $secs_elapsed -gt $MAX_START_WAIT_SECS ]]; then
-      echo "Error: Container has not started after ${MAX_START_WAIT_SECS} seconds."
-      exit 1
-    fi
-    echo 'Container is not ready. Sleeping for 5 seconds..'
-    sleep 5
-  done
-  echo "Container is ready."
-}
+SERVER_START_DEADLINE_SECS=300
+CLIENT_CONNECT_DEADLINE_SECS=30
 
 function start_container() {
   echo "Starting container.."
@@ -38,48 +20,41 @@ function start_container() {
       demonchild2112/grr
 }
 
+function wait_for_container_to_start() {
+  echo "Waiting for container to start.."
+  poll_start=$(date +%s)
+  while true; do
+    ready_msg="$(docker logs ${CONTAINER} 2>&1 | perl -wln -e 'print if /\bAdmin UI gui is at\b/')"
+    if [[ ! -z "${ready_msg}" ]]; then
+      break
+    fi
+    secs_elapsed=$(( $(date +%s) - $poll_start ))
+    if [[ $secs_elapsed -gt $SERVER_START_DEADLINE_SECS ]]; then
+      echo "Error: Container has not started after ${SERVER_START_DEADLINE_SECS} seconds."
+      exit 1
+    fi
+    echo 'Container is not ready. Sleeping for 5 seconds..'
+    sleep 5
+  done
+  echo "Container is ready."
+}
+
 start_container
 
 wait_for_container_to_start
 
-docker cp docker/fake-systemctl.sh $CONTAINER:/bin/systemctl
+docker cp docker/fake-systemctl.sh "${CONTAINER}":/bin/systemctl
 
-xenial_installer="$(docker exec $CONTAINER ls /usr/share/grr-server/executables/installers | grep -e grr_.*_amd64.deb)"
+xenial_installer="$(docker exec ${CONTAINER} ls /usr/share/grr-server/executables/installers | grep -e grr_.*_amd64.deb)"
 
-docker exec $CONTAINER dpkg -i /usr/share/grr-server/executables/installers/$xenial_installer
+docker exec "${CONTAINER}" dpkg -i "/usr/share/grr-server/executables/installers/${xenial_installer}"
 
 echo "Waiting for server to connect to client."
 
-sleep 20
+sleep ${CLIENT_CONNECT_DEADLINE_SECS}
 
 echo "Fetching client id."
 
 client_id="$(docker exec ${CONTAINER} /usr/share/grr-server/bin/grr_console --code_to_execute 'print(str(client_index.CreateClientIndex().LookupClients([])[0]))')"
 
-docker exec $CONTAINER useradd -m grrbot
-
-docker exec $CONTAINER /usr/share/grr-server/bin/grr_end_to_end_tests --client_ids $client_id 2>&1 | tee xenial_end_to_end.log
-
-#docker exec $CONTAINER sed -i 's/exit 101/exit 0/g' /usr/sbin/policy-rc.d
-
-#docker cp grr_container:/usr/share/grr-server/executables/installers/grr_3.2.0.0_amd64.deb .
-
-#dpkg -i grr_3.2.0.0_amd64.deb
-
-#service grr status
-
-#sleep 20
-
-#docker logs "${CONTAINER}" 1>container.log 2>&1
-
-#cat container.log
-
-#apt install -y wget
-
-#docker ps -a
-
-#wget ${DOCKER_IP}:8080/server.pem
-
-#cat server.pem
-
-#docker exec "${CONTAINER}" /usr/share/grr-server/bin/grr_console --code_to_execute "print(client_index.CreateClientIndex().LookupClients([]))"
+docker exec "${CONTAINER}" /usr/share/grr-server/bin/grr_end_to_end_tests --client_ids $client_id 2>&1 | tee xenial_end_to_end.log
